Handling lists
ljaro/cutest pull request #18
Opened 2019-09-03 06:31 UTC by ljaro

2019-09-04 10:13 UTC, van9konst requested changes
please rebase to letest dev, and remove commit "Relative imports changed to absolute"

2019-09-09 07:43 UTC, ljaro commented
> please rebase to letest dev, and remove commit "Relative imports changed to absolute"

done.

Please also run some tests to check regression

2019-09-09 09:07 UTC, van9konst requested changes

2019-09-09 09:07 UTC, van9konst commented on cutestpy/object_factory.py
> +    	return new_obj
wrong amount of spaces. Please reformat code

2019-09-09 09:12 UTC, van9konst approved these changes

2019-09-09 09:12 UTC, merged